const prohibitedIngredients = [
  'cissus',
  'bovine',
  'bovine gelatin',
  'beef gelatin',
  'cow gelatin',
  'raspberry ketones',
  'pygeum',
  'magnolia bark extract',
  'magnolia bark',
  'magnolia',
  'sibutramine',
  'cbd',
  'cannabidiol',
  'white willow bark',
  'white willow',
  'goldenseal root extract',
  'goldenseal root',
  'lithium',
  'mucuna pruriens seed extract',
  'mucuna pruriens seed',
  'mucuna pruriens',
  'slippery elm bark',
  'slippery elm',
  'slippery',
  'azorubine',
  'bovine',
  'bovine gelatin',
  'beef gelatin',
  'cow gelatin',
  'bse',
  'glutathione',
  '5-htp',
  '5-hydroxytryptophan',
  'griffonia',
  'griffonia simplicifolia seed extract',
  'griffonia simplicifolia seed',
  'griffonia simplicifolia',
  'acetyl-l-carnitine',
  'n-acetyl-l-carnitine 3',
  'agmatine sulfate',
  'agmapure',
  'alpha-lipoic acid',
  'alpha-lipoic',
  'ala',
  'α-lipoic acid',
  'α-lipoic',
  'r-lipoic acid',
  'r-lipoic',
  'lipoic acid',
  'lipoic',
  'aphanizomenon flos-aquae',
  'aphanizomenon flos',
  'afa',
  'microcystin',
  'arachidonic acid',
  'arachidonic',
  'bacopa',
  'brahmi',
  'berberine',
  'black cohosh',
  'black snake root',
  'black snake',
  'actaea racemosa',
  'cimicifuga recomosa',
  'recomosa',
  'buckthorn',
  'rhamnus frangula bark',
  'rhamnus frangula',
  'butea superba',
  'creeping butea',
  'butea gum tree',
  'butea gum',
  'redkwaokrua',
  'butterfly pea',
  "cat's claw",
  'cats claw',
  'cat claw',
  "cat'sclaw",
  'catsclaw',
  'catclaw',
  'uncaria tomentosa',
  'catuaba',
  'charcoal',
  'activated charcoal',
  'chromium picolinate',
  'citicoline',
  'cognizen',
  'clubmoss extract',
  'clubmoss',
  'chinese clubmoss',
  "colt's foot",
  'colts foot',
  'colt foot',
  "colt'sfoot",
  'coltsfoot',
  'coltfoot',
  'farfarae flos',
  "ass's foot",
  'ass foot',
  'asss foot',
  "ass'sfoot",
  'assfoot',
  'asssfoot',
  "bull's foot",
  'bulls foot',
  'bull foot',
  "bull'sfoot",
  'bullsfoot',
  'bullfoot',
  'coughwort',
  'farfara',
  "foal's wort",
  'foal wort',
  'foals wort',
  "foal'swort",
  'foalwort',
  'foalswort',
  'fieldhove',
  'horse',
  "horse's hoof",
  'horses hoof',
  'horse hoof',
  'horse-foot',
  'horse-shoe',
  'horsehoof',
  'tussilago farfara linne',
  "devil's claw root",
  "devil's claw",
  'devil claw root',
  'devil claw',
  'harpagophytum procumbens',
  'dhea',
  'dehydroepiandrosterone',
  'diindolylmethane',
  'dim',
  'diosmin',
  'echinacea spp',
  'epimedium sagittatum',
  'epimedium grandiflorum',
  'horny goat weed',
  'horny goat',
  'forsythia suspensa extract',
  'forsythia suspensa fruit',
  'forsythia suspensa',
  'fur seal',
  'gamma-aminobutyric acid',
  'gaba',
  'garcinia quaesita',
  'germanium',
  'goldenseal root',
  'goldenseal',
  'ox-eye daisy',
  'guggul extract',
  'guggul resin',
  'guggul',
  'guggulsterones',
  'gymnema sylvestre',
  'hemp',
  'cannabis sativa l.',
  'cannabis sativa l',
  'histamine',
  'histamine hydrochloride',
  'histamine hcl',
  'horse chestnut',
  'icariin',
  'indian snake root',
  'indian snake',
  'rauwolfia serpentina',
  'kaempferia parviflora',
  'kava kava',
  'kava',
  'kawa kawa',
  'kawa',
  'kavain',
  'l-citrulline',
  'citrulline malate',
  'lobelia',
  'rhodea japonica roth',
  'longjack',
  'eurycoma longifolia',
  'tongkat ali',
  'l-ornithine',
  'l-selenomethionine',
  'magnesium citrate',
  'magnolia',
  'magnolia officinalis',
  'magnolia officinalis extract',
  'mamushi',
  'melatonin',
  'methylcobalamin',
  'methyl-b12',
  'active-b12',
  'l-dopa',
  'montanoa',
  'montanoa tomentosa',
  'muira puama',
  'ptychopetalum olacoides',
  'n-acetyl-cysteine',
  'nac',
  'n-acetyl-l-cysteine',
  'orlistat',
  'para-aminobenzoic acid',
  'paba',
  'phellodendri cortex',
  'phellodendron',
  'phellodendron bark',
  'phellodendron amurense ruprecht',
  'phellodendron chinense',
  'schneider',
  'phenylethylamine',
  'pea',
  'β-phenylethylamine',
  'β-pea,',
  '2-phenethylamine',
  'β-phenethylamine·hydrochloride',
  'β-pea·hcl',
  'pinellia tuber',
  'pinellia ternata breitenbach',
  'pomegranate seed',
  'pomegranate bark',
  'pomegranate',
  'poppy',
  'papaver somniferum',
  'pueraria mirifica',
  'pygeum africanum',
  'pygeum africanum bark',
  'raspberry ketone',
  'rhubarb',
  'rheum palmatum',
  'rheum tanguticum',
  'rheum officinale bailon',
  'salacia',
  'scorpion',
  'scorpio',
  'buthus martensii karsch',
  'senna',
  'silver',
  'slippery elm',
  'ulmus rubra',
  'synephrine',
  'vervain',
  'verbena',
  'verbanalin',
  'vinpocetine',
  'vinca minor',
  'lesser periwinkle',
  'vitamin k2',
  'k2',
  'menaquinone',
  'mk-4',
  'mk-7',
  'white willow',
  'salix alba',
  'wild yam',
  'yohimbe',
  'yohimbin',
  'zinc citrate',
  'e131 patent blue v',
  'mucuna pruriens seed',
  'magnesium glycinate',
  'magnesium diglycinate',
  'magnesium bisglycinate',
  '1,3-dimethylamylamine',
  'dmaa',
  '1,3-dimethylbutylamine',
  'dmba',
  'acetaminotadalafil',
  'acetyl acid',
  'acetylvardenafil',
  'adrenaline',
  'epinephrine',
  'ajuga decumbens',
  'aminotadalafil',
  'anemarrhennae asphodelides',
  'avanafil',
  'belladonna',
  'atropa belladonna',
  'benzylsildenafil',
  'bergenin',
  'buchu leaf',
  'buchu',
  'agathosma betulina',
  'agathosma creunlata',
  'caesalpinia benthamiana',
  'carbodenafil',
  'cascara sagrada',
  'cascaroside',
  'cha de bugre',
  'cha de bugre herb powder',
  'chlorodenafil',
  'chloropretadalafil',
  'chlorosibutramine',
  'chlorosipentramine',
  'chromium argninate',
  'cinnamyldenafil',
  'cis-cyclopentyltadalafil',
  'cordia salicifolia',
  'couch grass',
  'agropyron repens',
  'elymus repens',
  'cyanotis vaga',
  'cyclopentynafil',
  'd-chlorpheniramine',
  'demethylhongdenafil',
  'demethyltadalafil',
  'descarbonsildenafil',
  'desmethylcarbodenafil',
  'desmethylsibutramine',
  'desulfovardenafil',
  'dexamethasone',
  'dichlorodenafil',
  'didesmethylsibutramine',
  'dimethylsildenafil',
  'dimethylthiosildenafil',
  'dithiopropylcarbodenafil',
  'dolmite',
  'dnp',
  'dinitrophenyl',
  'dinitrophenol',
  'ebony',
  'ephedrine',
  'fenfluramine',
  'fluoxetine',
  'fucoxanthin',
  'furosemide',
  'gelsemium sempervirens',
  'gendenafil',
  'glibenclamide',
  'gliclazide',
  'glimepiride',
  'glipizide',
  'gravel root',
  'gravel',
  'homosildenafil',
  'homotadalafil',
  'hongdenafil',
  'hoodia cactus powder',
  'hoodia cactus',
  'hoodia gordonii',
  'hydroxychlorodenafil',
  'hydroxyhomosildenafil',
  'hydroxyhongdenafil',
  'hydroxythiohomosildenafil',
  'hydroxyvardenafil',
  'imidazosagtriazinone',
  'isopropylnortadalafil',
  'levothyroxine',
  'ligustrum berry',
  'liothyronine',
  'lumbrokinase',
  'methylhydroxyhomosildenafil',
  'mirodenafil',
  'nitrodenafil',
  'n-nitrosofenfluramine',
  'n-octylnortadalafil',
  'norneosildenafil',
  'norneovardenafil',
  'oxilofrine',
  'oxohongdenafil',
  'phenolphthalein',
  'piperidinohongdenafil',
  'prickly chaff',
  'achyranthes aspera',
  'achyranthes aspera flower',
  'achyranthes aspera flower extract',
  'propoxyphenyl-thioaildenafil',
  'propoxyphenylthiohomosildenafil',
  'propoxyphenylthiohydroxyhomosildenafil',
  'propoxyphenylthiosildenafil',
  'pseudovardenafil',
  'radix morindae officinalis',
  'red root bark',
  'red root',
  'quinna tree bark',
  'quinna tree',
  'cichona bark',
  'cichona',
  'pavonetklotzsch',
  'rhaponticum carthamoides',
  'seman pruni',
  'sennoside',
  'sibutramine',
  'sildenafil',
  'tadalafil',
  'thiohomosildenafil',
  'thioquinapiperifil',
  'thiosildenafil',
  'trans-cyclopentyltadalafil',
  'trichopus zeylanicus',
  'udenafil',
  'vardenafil',
  'veratrum',
  'white hellebore',
  'veratri rhizoma et radix',
  'veratri rhizoma',
  'xanthoanthrafil',
  'β-methylphenethylamine·hydrochloride',
  'β-methylphenethylamine',
  'β-mpea·hcl',
  'β-methylphenethylamine',
  'β-mpea',
  'orthosiphon stamineus',
  'sildenafil',
  'tadalafil',
  'vardenafil',
  'udenafil',
  'mirodenafil',
  'avanafil',
  'homosildenafil',
  'hongdenafil',
  'hydroxy homosildenafil',
  'amino tadalafil',
  'pseudo-vardenafil',
  'hydroxy hongdenafil',
  'dimethylsildenafil',
  'xanthoanthrafil',
  'hydroxyvadenafil',
  'norneosildenafil',
  'demethylhongdenafil',
  'piperidinohongdenafil',
  'carbodenafil',
  'thiosildenafil',
  'dimethylthiosildenafil',
  'acetylvardenafil',
  'benzylsildenafil',
  'norneovardenafil',
  'oxohongdenafil',
  'thiohomosildenafil',
  'desulfovardenafil',
  'nitrodenafil',
  'cyclopentynafil',
  'octylnortadalafil',
  'cinnamyldenafil',
  'thioquinapiperifil',
  'hydroxythiohomosildenafil',
  'chloropretadalafil',
  'hydroxychlorodenafil',
  'dichlorodenafil',
  'demethyltadalafil',
  'acetaminotadalafil',
  'methylhydroxyhomosildenafil',
  'propoxyphenylthiosildenafil',
  'propoxyphenylthiohydroxyhomosildenafil',
  'propoxyphenylthiosildenafil',
  'propoxyphenylthioaildenafil',
  'homotadalafil',
  'acetyl acid',
  'gendenafil',
  'imidazosagatriazinone',
  'cis-cyclopentyltadalafil',
  'cyclopentyltadalafil',
  'trans-cyclopentyltadalafil',
  'cyclopentyltadalafil',
  'isopropylnortadalafil',
  'descarbonsildenafil',
  'dithiopropylcarbodenafil',
  'sibutramine',
  'orlistat',
  'desmethylsibutramine',
  'didesmethylsibutramine',
  'chlorosibutramine',
  'chlorosipentramine',
  'glibenclamide',
  'gliclazide',
  'glimepiride',
  'glipizide',
  't3',
  't4',
  'ephedrine',
  'fluoxetine',
  'fenfluramine',
  'n-nitrosofenfluramine',
  'phenolphthaleine',
  'yohimbine',
  'icarine',
  'sennoside',
  'cascaroside',
  'chelated',
  'chelate',
  'chelated magnesium',
  'cassia occidentalis',
  'cassia',
  'terminalia arjuna',
  'terminalia',
  'andrographis',
  'phyllanthus amarus',
  'phyllanthus',
  'shilajit',
  'buchu leaf',
  'agathosma betulina',
  'agathosma creunlata',
  'agathosma',
  'echinacea',
  'forsythia',
  'tejocote root',
  'tejocote',
  'crataegus mexicana',
  'crataegus',
];

export default prohibitedIngredients;
